AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "VPC"

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24" 
      AvailabilityZone: !Select [0, !GetAZs ""]  # First availability zone
      Tags:
        - Key: Name
          Value: "PublicSubnet"

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !Ref VPC
  PublicSubnetId:
    Description: "Public Subnet ID"
    Value: !Ref PublicSubnet